name = "galaxyvless"
main = "_worker.js"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]

[vars]
UUID = ""
PROXYIP = "cdn-b100.xn--b6gac.eu.org"
PROXY_LIST_URL = "https://raw.githubusercontent.com/gprox-galaxy/Gproxy-domaip/refs/heads/main/PROXYIP.txt"
DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
