name = "galaxyvless" 
main = "_worker.js"
compatibility_date = "2024-03-20"

# Cloudflare Sockets / Node.js Compatibility အတွက် ထည့်သွင်းရန်
compatibility_flags = [ "nodejs_compat" ]

# Environment Variables (အပြောင်းအလဲလုပ်လိုသော ကိန်းရှင်များ)
[vars]
# ⚠️ သင့်ရဲ့ သီးသန့် UUID ကို ဒီမှာ အစားထိုးပါ (သို့မဟုတ် Cloudflare Dashboard ထဲမှာ Setting ပြင်နိုင်သည်)
UUID = " "

# Fallback Proxy IP
PROXYIP = "cdn-b100.xn--b6gac.eu.org"

# သင့် GitHub Repository ပေါ်က PROXYIP.txt ရဲ့ Raw Link ကို ပြင်ဆင်ပါ
PROXY_LIST_URL = "https://raw.githubusercontent.com/gprox-galaxy/Gproxy-domaip/refs/heads/main/PROXYIP.txt"

# DoH DNS Resolver
DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
